name: Fork Notification
run-name: Notify Slack on Fork

on:
  fork:  # Trigger the workflow on fork events

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Slack
        run: |
          echo "Sending Slack notification..."
          curl https://hooks.slack.com/services/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   -X POST -H 'Content-type: application/json' --data '{
            "text": "The repository *${{ github.repository }}* was forked by *${{ github.actor }}*."
          }'


          
