name: mynodejs
run-name: ninjas-workout

on: [push]

jobs:
  clone_app:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Cloning app - ninjasworkout"
        run: git clone https://github.com/effortlessdevsec/ninjasworkout.git
      
      - name: "Change directory and list files"
        run: |
          cd ninjasworkout
          ls
