name: mynodejs
run-name: ninjas-workout

on: [push]

jobs:
  clone_app:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Cloning app - ninjasworkout"
        run: |
          git clone https://github.com/effortlessdevsec/ninjasworkout.git
          cd ninjasworkout
      
      - name: "Showing all files"
        run: ls
